#!/bin/bash
Trash="/tmp/.Trash"
Date=`date +%F`
UnixTS=`date +%s`
Days="+3"

# 清理超过三天的数据，清理后创建一个标识文件在当天的目录下，避免一天内重复清理操作
[ ! -f ${Trash}/${Date}/clean ] && find  ${Trash} -ctime ${Days} |xargs rm -rf {} && touch ${Trash}/${Date}/clean
    

# 被删除的文件及目录会存放/tmp/.Trash下，当天日期的文件夹内
# 为避免文件名重复，文件名前面加上了Unix时间戳
[ -d ${Trash}/${Date} ] || mkdir -p ${Trash}/${Date}
for file in `echo $*`
do
    mv $file ${Trash}/${Date}/${UnixTS}-${file}
done

# Unix时间戳换正常时间
# date -d @时间戳

